# Generated by Django 3.2.3 on 2021-06-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecificationvalue',
            name='product_type',
        ),
    ]
